# pre-commit run --all-files
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: "resources/.*"
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-added-large-files
        args: ['--maxkb=1000']
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ["--ignore", "E,W,F"]
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.942
#     hooks:
#     -   id: mypy
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        additional_dependencies: [toml]
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        args: [--target-version, py36]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.1.0]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
